name: Python application

on:
  push:
    branches: [ "developer", "main" ]
  pull_request:
    branches: [ "developer", "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir --force-reinstall -r requirements.txt
        pip list  # Debugging: Show installed packages

    - name: Check if dotenv is installed
      run: python -c "import dotenv; print('dotenv is installed')"

    - name: Test with pytest --pylint
      run: |
        pytest -v
